### PR TITLE
Fix frameskip bug and add Minitaur controllers

### PR DESCRIPTION
**Pull request by glewis17**
Fixed frameskip bug as described in #47 .  I added a `controller = None` property to `BaseRobot`, then in  `BaseRobotEnv._step`, we loop `frame_skip` times on transforming the action `a` with the controller (or pass through if none exists). Pybullet simulates for `timestep` time in each loop iteration.

Verified working with Minitaur, Husky, and drone at frameskips of 1, 10, and 100.

### CODE REVIEW

**Comment by fxia22** [comment]
We will carefully review this PR, it seems to change our definition of timestep and frameskip.

**Comment by hzyjerry** [comment]
I notice the modification to `p.setPhysicsEngineParameter`. At the same time, `p.stepSimulation()` is only called once per environment step.  I wonder if this will cause the physical simulation to ignore `frame_skip`.

**Comment by glewis17** [comment]
@hzyjerry In the PR, we call `scene.global_step` for `frame_skip` times in each environment step, so the physical simulation runs `timestep * frame_skip` seconds like before. The only difference is now the inputs to the robot are allowed to vary between each of the `frame_skip` steps in a single environment step. This is useful if the action space is a high-level command that runs slowly relative to a low-level controller (in this case, the controller that issues commands for minitaur legs).

**Comment by fxia22** [comment]
Merged into dev for testing. Thanks @glewis17 for the contribution.

**Pull request closed without merging**
